---
title: "Music Insights"
author: Jennifer Griffiths
output: html_notebook
---

##First we need to install tidyverse

```{r eval=FALSE, warning=FALSE}
install.packages("tidyverse")
library(tidyverse)

# LOAD THE DATA
survey <- read_csv("https://raw.githubusercontent.com/introdsci/MusicSurvey/master/music-survey.csv")

preferences <- read_csv("https://raw.githubusercontent.com/introdsci/MusicSurvey/master/preferences-survey.csv")
```

## Inspecting the Data
```{r}
#View Data
View(preferences)
View(survey)

#Count of rows
nrow(preferences)
#Count of columns
ncol(preferences)
```

#Tidy data for Person and FavoriteSong tables
###Changing the name of the columns in Survey dataframe
 
```{r}
# pseudonym
colnames(survey)[colnames(survey) == "What is your pseudonym?" ] <- "pseudonym"

# pseudonym_generator
colnames(survey)[colnames(survey)== "First, we are going to create a pseudonym for you to keep this survey anonymous (more or less). Which pseudonym generator would you prefer?"] <- "pseudonym_generator"

#time_submitted
colnames(survey)[colnames(survey) == "Timestamp" ] <- "time_submitted"

#sex
colnames(survey)[colnames(survey) == "Sex" ] <- "sex"

#academic_major
colnames(survey)[colnames(survey) == "Major" ] <- "academic_major"

#year_born
colnames(survey)[colnames(survey) == "Year you were born (YYYY)" ] <- "year_born"

#academic_level
colnames(survey)[colnames(survey) == "Academic Year" ] <- "academic_level"

#instrument_list
colnames(survey)[colnames(survey) == "Which musical instruments/talents do you play? (Select all that apply)" ] <- "instrument_list"

#favorite_song_artist
colnames(survey)[colnames(survey) == "Artist" ] <- "favorite_song_artist"

#favorite_song
colnames(survey)[colnames(survey) == "Song" ] <- "favorite_song"

#favorite_song_link
colnames(survey)[colnames(survey) == "Link to song (on Youtube or Vimeo)" ] <- "favorite_song_link"
```

###Load dplyr and tidyr libraries

```{r}
library("dplyr")
library("tidyr")
```

#Create Tables Using Tibble
##Person Tibble
```{r message=FALSE, warning=FALSE}
Person <- tibble(time_submitted = survey$time_submitted, pseudonym = survey$pseudonym, generator_name =  survey$pseudonym_generator, sex = survey$sex, academic_major = survey$academic_major,year_born = survey$year_born)
```

###Updating the format of date time
```{r}
#load library
library(readr)
#formatting options in help page
?parse_datetime

#Converting 'time_submitted' to POSIX lt(local time)
Person$time_submitted <- as.POSIXlt(parse_datetime(Person$time_submitted, "%m/%d/%y %H:%M"))

#check updated format at index 1
Person$time_submitted[1]
#check portions of updated format at index 1
Person$time_submitted[1]$hour
Person$time_submitted[1]$min
```

##FavoriteSong Tibble
```{r}
FavoriteSong <- tibble(pseudonym = survey$pseudonym, artist =  survey$favorite_song_artist, song = survey$favorite_song, song_link = survey$favorite_song_link )
```

#Tidy data for Ratings table
```{r}

```

##Ratings Tibble
```{r}
#Ratings <- tibble()
```
#Using Tidyr to clean up 

```{r}
#gather()
#spread()
```

```{r}

```



